services:
  app:
    image: ghcr.io/docjyj/simple-craft-admin:main
    container_name: simple-craft-admin
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '80:3000'
    volumes:
      - simple_craft_admin_config:/app/config
      - simple_craft_admin_minecraft:/app/minecraft
    restart: unless-stopped

volumes:
  simple_craft_admin_config:
  simple_craft_admin_minecraft:
